name: Feature Request
description: 提出功能请求。
title: '[Feat]: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 请清晰地描述问题所在。
      placeholder: 比如：当[...]时，会遇到[...]问题
  - type: textarea
    id: solution
    attributes:
      label: 解决方案
      description: 请清晰地描述您想要怎么做。
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 请描述您考虑过的备选方案。
  - type: textarea
    id: context
    attributes:
      label: 附加上下文
      description: 在此处添加有关功能请求的任何其他上下文或屏幕截图。
